name: Sync Releases
on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to sync
        default: wxt
        type: choice
        options:
          - auto-icons
          - i18n
          - module-react
          - module-solid
          - module-svelte
          - module-vue
          - storage
          - wxt

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          installArgs: --ignore-scripts
      - run: pnpm tsx scripts/sync-releases.ts ${{ inputs.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
