name: vhs
on:
  push:
    paths:
      - 'docs/tapes/*.tape'
  workflow_dispatch:

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm store add wxt@latest
        
      - uses: charmbracelet/vhs-action@v2.1.0
        with:
          path: 'docs/tapes/demo.tape'

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          branch: ${{ github.head_ref || github.ref_name }}
          # https://github.com/charmbracelet/vhs#output
          file_pattern: 'docs/public/*.gif'
